before_script:
  - psql -c 'create database spotify-time-machine_test;' -U postgres
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - postgresql
